import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../common/styles/colors.dart';
import '../../../domain/entities/course_entity.dart';
import '../../../domain/entities/forum_topic_entity.dart';
import '../../../domain/entities/forum_reply_entity.dart';
import '../../providers/forum_topic_provider.dart';
import '../../providers/forum_reply_provider.dart';
import '../../providers/auth_provider.dart';
import 'widgets/topic_form_dialog.dart';
import 'widgets/reply_widget.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../../domain/entities/user_entity.dart';

/// Forum Topic Detail Screen - displays topic and all replies
class ForumTopicDetailScreen extends ConsumerStatefulWidget {
  final CourseEntity course;
  final String topicId;

  const ForumTopicDetailScreen({
    super.key,
    required this.course,
    required this.topicId,
  });

  @override
  ConsumerState<ForumTopicDetailScreen> createState() =>
      _ForumTopicDetailScreenState();
}

class _ForumTopicDetailScreenState
    extends ConsumerState<ForumTopicDetailScreen> {
  final TextEditingController _replyController = TextEditingController();
  final ScrollController _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        ref.read(forumReplyProvider.notifier).loadReplies(widget.topicId);
      }
    });
  }

  @override
  void dispose() {
    _replyController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  Future<String?> _getUserName(String userId) async {
    try {
      final userDoc = await FirebaseFirestore.instance
          .collection('users')
          .doc(userId)
          .get();
      if (userDoc.exists) {
        return userDoc.data()?['displayName'] as String? ?? 'Unknown User';
      }
    } catch (e) {
      // Error getting user name
    }
    return 'Unknown User';
  }

  void _sendReply() {
    final content = _replyController.text.trim();
    if (content.isEmpty) return;

    final user = ref.read(authProvider).value;
    if (user == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('You must be logged in to reply'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    final reply = ForumReplyEntity(
      id: '', // Will be generated by repository
      topicId: widget.topicId,
      content: content,
      authorId: user.uid,
      createdAt: DateTime.now(),
    );

    ref.read(forumReplyProvider.notifier).createReply(reply).then((_) {
      _replyController.clear();
      // Scroll to bottom to show new reply
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    }).catchError((error) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error sending reply: ${error.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    });
  }

  void _deleteTopic(ForumTopicEntity topic) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(
          'Delete Topic',
          style: GoogleFonts.inter(fontWeight: FontWeight.bold),
        ),
        content: Text(
          'Are you sure you want to delete "${topic.title}"? This action cannot be undone.',
          style: GoogleFonts.inter(),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: Text('Cancel', style: GoogleFonts.inter()),
          ),
          ElevatedButton(
            onPressed: () async {
              final navigator = Navigator.of(context);
              final messenger = ScaffoldMessenger.of(context);
              navigator.pop();
              try {
                await ref
                    .read(forumTopicProvider.notifier)
                    .deleteTopic(topic.id);
                if (mounted) {
                  navigator.pop(); // Go back to list
                }
              } catch (e) {
                if (mounted) {
                  messenger.showSnackBar(
                    SnackBar(
                      content: Text('Error: ${e.toString()}'),
                      backgroundColor: Colors.red,
                    ),
                  );
                }
              }
            },
            style: ElevatedButton.styleFrom(backgroundColor: Colors.red),
            child: Text(
              'Delete',
              style: GoogleFonts.inter(color: Colors.white),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final topicAsync = ref.watch(forumTopicByIdProvider(widget.topicId));
    final repliesAsync = ref.watch(forumReplyProvider);
    final userAsync = ref.watch(authProvider);

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: AppColors.textPrimary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Topic',
          style: GoogleFonts.inter(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: AppColors.textPrimary,
          ),
        ),
        actions: [
          topicAsync.when(
            data: (topic) {
              if (topic == null) return const SizedBox.shrink();
              final user = userAsync.value;
              final isAuthor = user?.uid == topic.authorId;
              final isInstructor = user?.role == UserRole.instructor;

              if (isAuthor || isInstructor) {
                return PopupMenuButton(
                  icon: const Icon(Icons.more_vert, color: AppColors.textPrimary),
                  itemBuilder: (context) => [
                    if (isAuthor)
                      PopupMenuItem(
                        child: const Row(
                          children: [
                            Icon(Icons.edit, size: 20),
                            SizedBox(width: 8),
                            Text('Edit'),
                          ],
                        ),
                        onTap: () {
                          final navigatorContext = context;
                          Future.delayed(const Duration(milliseconds: 100), () {
                            if (mounted && navigatorContext.mounted) {
                              _showTopicDialog(navigatorContext, topic);
                            }
                          });
                        },
                      ),
                    PopupMenuItem(
                      child: const Row(
                        children: [
                          Icon(Icons.delete, size: 20, color: Colors.red),
                          SizedBox(width: 8),
                          Text('Delete', style: TextStyle(color: Colors.red)),
                        ],
                      ),
                      onTap: () {
                        Future.delayed(const Duration(milliseconds: 100), () {
                          if (mounted) {
                            _deleteTopic(topic);
                          }
                        });
                      },
                    ),
                  ],
                );
              }
              return const SizedBox.shrink();
            },
            loading: () => const SizedBox.shrink(),
            error: (_, __) => const SizedBox.shrink(),
          ),
        ],
      ),
      body: topicAsync.when(
        data: (topic) {
          if (topic == null) {
            return Center(
              child: Text(
                'Topic not found',
                style: GoogleFonts.inter(fontSize: 18),
              ),
            );
          }

          return Column(
            children: [
              // Topic content
              Expanded(
                child: SingleChildScrollView(
                  controller: _scrollController,
                  padding: const EdgeInsets.all(24),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Topic card
                      _buildTopicCard(topic),
                      const SizedBox(height: 24),
                      // Replies section
                      Text(
                        'Replies',
                        style: GoogleFonts.inter(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                          color: AppColors.textPrimary,
                        ),
                      ),
                      const SizedBox(height: 16),
                      // Replies list
                      repliesAsync.when(
                        data: (replies) {
                          if (replies.isEmpty) {
                            return Padding(
                              padding: const EdgeInsets.symmetric(vertical: 32),
                              child: Center(
                                child: Text(
                                  'No replies yet. Be the first to reply!',
                                  style: GoogleFonts.inter(
                                    fontSize: 14,
                                    color: AppColors.textSecondary,
                                  ),
                                ),
                              ),
                            );
                          }

                          // Build reply tree (handle threaded replies)
                          return _buildReplyTree(replies);
                        },
                        loading: () => const Padding(
                          padding: EdgeInsets.symmetric(vertical: 32),
                          child: Center(child: CircularProgressIndicator()),
                        ),
                        error: (error, _) => Padding(
                          padding: const EdgeInsets.symmetric(vertical: 32),
                          child: Center(
                            child: Text(
                              'Error loading replies: ${error.toString()}',
                              style: GoogleFonts.inter(
                                fontSize: 14,
                                color: Colors.red,
                              ),
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(height: 80), // Space for reply input
                    ],
                  ),
                ),
              ),
              // Reply input
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: AppColors.cardBackground,
                  border: Border(
                    top: BorderSide(color: AppColors.border),
                  ),
                ),
                child: SafeArea(
                  child: Row(
                    children: [
                      Expanded(
                        child: TextField(
                          controller: _replyController,
                          decoration: InputDecoration(
                            hintText: 'Write a reply...',
                            hintStyle: GoogleFonts.inter(fontSize: 14),
                            filled: true,
                            fillColor: AppColors.background,
                            contentPadding: const EdgeInsets.symmetric(
                              horizontal: 16,
                              vertical: 12,
                            ),
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(24),
                              borderSide: const BorderSide(color: AppColors.border),
                            ),
                            enabledBorder: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(24),
                              borderSide: const BorderSide(color: AppColors.border),
                            ),
                          ),
                          style: GoogleFonts.inter(fontSize: 14),
                          maxLines: null,
                          textInputAction: TextInputAction.send,
                          onSubmitted: (_) => _sendReply(),
                        ),
                      ),
                      const SizedBox(width: 8),
                      IconButton(
                        onPressed: _sendReply,
                        icon: const Icon(Icons.send),
                        color: AppColors.buttonPrimary,
                        style: IconButton.styleFrom(
                          backgroundColor: AppColors.buttonPrimary.withValues(alpha: 0.1),
                          padding: const EdgeInsets.all(12),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (error, _) => Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.error_outline, size: 48, color: Colors.red),
              const SizedBox(height: 16),
              Text(
                'Error loading topic',
                style: GoogleFonts.inter(
                  fontSize: 18,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                error.toString(),
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(fontSize: 14),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTopicCard(ForumTopicEntity topic) {
    return FutureBuilder<String?>(
      future: _getUserName(topic.authorId),
      builder: (context, snapshot) {
        final authorName = snapshot.data ?? 'Unknown User';

        return Card(
          color: AppColors.cardBackground,
          elevation: 0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
            side: const BorderSide(color: AppColors.border),
          ),
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Title
                Text(
                  topic.title,
                  style: GoogleFonts.inter(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                    color: AppColors.textPrimary,
                  ),
                ),
                const SizedBox(height: 12),
                // Author and date
                Row(
                  children: [
                    CircleAvatar(
                      radius: 16,
                      backgroundColor: AppColors.background,
                      child: Text(
                        authorName[0].toUpperCase(),
                        style: GoogleFonts.inter(
                          fontSize: 12,
                          fontWeight: FontWeight.w600,
                          color: AppColors.textPrimary,
                        ),
                      ),
                    ),
                    const SizedBox(width: 8),
                    Text(
                      authorName,
                      style: GoogleFonts.inter(
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                        color: AppColors.textPrimary,
                      ),
                    ),
                    const SizedBox(width: 12),
                    Text(
                      _formatDate(topic.createdAt),
                      style: GoogleFonts.inter(
                        fontSize: 12,
                        color: AppColors.textSecondary,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 16),
                // Content
                Text(
                  topic.content,
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    color: AppColors.textPrimary,
                    height: 1.5,
                  ),
                ),
                // Attachments
                if (topic.hasAttachments) ...[
                  const SizedBox(height: 16),
                  Wrap(
                    spacing: 8,
                    runSpacing: 8,
                    children: topic.attachments.map((attachment) {
                      return Chip(
                        avatar: const Icon(Icons.attach_file, size: 16),
                        label: Text(
                          attachment.split('/').last,
                          style: GoogleFonts.inter(fontSize: 12),
                        ),
                        backgroundColor: AppColors.background,
                      );
                    }).toList(),
                  ),
                ],
              ],
            ),
          ),
        );
      },
    );
  }

  Widget _buildReplyTree(List<ForumReplyEntity> replies) {
    // Separate top-level replies from threaded replies
    final topLevelReplies = replies.where((r) => r.replyToId == null).toList();
    final threadedReplies = replies.where((r) => r.replyToId != null).toList();

    // Build reply map for quick lookup
    final replyMap = <String, List<ForumReplyEntity>>{};
    for (var reply in threadedReplies) {
      replyMap.putIfAbsent(reply.replyToId!, () => []).add(reply);
    }

    // Build tree recursively
    Widget buildReplyTree(ForumReplyEntity reply, int depth) {
      final children = replyMap[reply.id] ?? [];
      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ReplyWidget(
            reply: reply,
            topicId: widget.topicId,
            depth: depth,
            onReplyUpdated: () {
              ref.read(forumReplyProvider.notifier).loadReplies(widget.topicId);
            },
          ),
          if (children.isNotEmpty) ...[
            const SizedBox(height: 8),
            Padding(
              padding: EdgeInsets.only(left: (depth + 1) * 24.0),
              child: Column(
                children: children
                    .map((child) => buildReplyTree(child, depth + 1))
                    .toList(),
              ),
            ),
          ],
        ],
      );
    }

    return Column(
      children: topLevelReplies
          .map((reply) => buildReplyTree(reply, 0))
          .toList(),
    );
  }

  String _formatDate(DateTime date) {
    final now = DateTime.now();
    final difference = now.difference(date);

    if (difference.inDays == 0) {
      if (difference.inHours == 0) {
        if (difference.inMinutes == 0) {
          return 'Just now';
        }
        return '${difference.inMinutes}m ago';
      }
      return '${difference.inHours}h ago';
    } else if (difference.inDays == 1) {
      return 'Yesterday';
    } else if (difference.inDays < 7) {
      return '${difference.inDays}d ago';
    } else {
      return '${date.day}/${date.month}/${date.year}';
    }
  }

  void _showTopicDialog(BuildContext context, ForumTopicEntity topic) {
    showDialog(
      context: context,
      builder: (context) => TopicFormDialog(
        course: widget.course,
        topic: topic,
      ),
    ).then((success) {
      if (mounted && success == true) {
        // Refresh topic and replies
        ref.read(forumTopicProvider.notifier).refresh();
        ref.read(forumReplyProvider.notifier).loadReplies(widget.topicId);
      }
    });
  }
}

