import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../../../domain/entities/assignment_entity.dart';
import '../../../../domain/entities/assignment_submission_entity.dart';
import '../../../common/styles/colors.dart';
import '../../../providers/assignment_submission_provider.dart';
import '../../../providers/auth_provider.dart';
import '../../../../services/file_upload_service.dart';

/// Dialog for submitting an assignment
class AssignmentSubmissionDialog extends ConsumerStatefulWidget {
  final AssignmentEntity assignment;
  final int attemptNumber;

  const AssignmentSubmissionDialog({
    super.key,
    required this.assignment,
    required this.attemptNumber,
  });

  @override
  ConsumerState<AssignmentSubmissionDialog> createState() =>
      _AssignmentSubmissionDialogState();
}

class _AssignmentSubmissionDialogState
    extends ConsumerState<AssignmentSubmissionDialog> {
  final _formKey = GlobalKey<FormState>();
  final List<String> _submittedFiles = [];
  late TextEditingController _fileUrlController;
  bool _isLoading = false;
  bool _isUploading = false;
  double _uploadProgress = 0.0;
  final FileUploadService _fileUploadService = FileUploadService();

  @override
  void initState() {
    super.initState();
    _fileUrlController = TextEditingController();
  }

  @override
  void dispose() {
    _fileUrlController.dispose();
    super.dispose();
  }

  void _addFileUrl() {
    final url = _fileUrlController.text.trim();
    if (url.isNotEmpty && !_submittedFiles.contains(url)) {
      setState(() {
        _submittedFiles.add(url);
        _fileUrlController.clear();
      });
    }
  }

  void _removeFile(String url) {
    setState(() {
      _submittedFiles.remove(url);
    });
  }

  Future<void> _pickAndUploadFiles() async {
    try {
      // Pick files
      final files = await _fileUploadService.pickFiles(allowMultiple: true);

      if (files == null || files.isEmpty) return;

      setState(() {
        _isUploading = true;
        _uploadProgress = 0.0;
      });

      // Upload files
      final uploadedUrls = await _fileUploadService.uploadMultipleFiles(
        files: files,
        path: 'courses/${widget.assignment.courseId}/assignments/submissions',
        onProgress: (current, total) {
          setState(() {
            _uploadProgress = current / total;
          });
        },
      );

      // Add uploaded URLs to submitted files
      setState(() {
        _submittedFiles.addAll(uploadedUrls);
        _isUploading = false;
        _uploadProgress = 0.0;
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${files.length} file(s) uploaded successfully'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      setState(() {
        _isUploading = false;
        _uploadProgress = 0.0;
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to upload files: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _submitAssignment() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    if (_submittedFiles.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please upload at least one file'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      final user = ref.read(authProvider).value;
      if (user == null) {
        throw Exception('User not logged in');
      }

      final now = DateTime.now();
      final isLate = now.isAfter(widget.assignment.deadline);

      SubmissionStatus status;
      if (isLate) {
        if (widget.assignment.lateDeadline != null &&
            now.isBefore(widget.assignment.lateDeadline!)) {
          status = SubmissionStatus.late;
        } else {
          throw Exception('Assignment deadline has passed');
        }
      } else {
        status = SubmissionStatus.submitted;
      }

      final submission = AssignmentSubmissionEntity(
        id: '', // Will be generated by Firestore
        assignmentId: widget.assignment.id,
        studentId: user.uid,
        courseId: widget.assignment.courseId,
        submissionTime: now,
        files: _submittedFiles,
        attemptNumber: widget.attemptNumber,
        status: status,
      );

      await ref
          .read(assignmentSubmissionProvider.notifier)
          .createSubmission(submission);

      if (!mounted) return;
      Navigator.of(context).pop(true);

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            isLate
                ? 'Assignment submitted late (Attempt ${widget.attemptNumber})'
                : 'Assignment submitted successfully (Attempt ${widget.attemptNumber})',
          ),
          backgroundColor: isLate ? Colors.orange : Colors.green,
        ),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error: ${e.toString()}'),
          backgroundColor: Colors.red,
        ),
      );
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final now = DateTime.now();
    final isBeforeStart = now.isBefore(widget.assignment.startDate);
    final isAfterDeadline = now.isAfter(widget.assignment.deadline);
    final isWithinLateDeadline =
        widget.assignment.lateDeadline != null &&
        now.isBefore(widget.assignment.lateDeadline!);

    return Dialog(
      backgroundColor: AppColors.cardBackground,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      child: Container(
        width: 700,
        constraints: const BoxConstraints(maxHeight: 900),
        padding: const EdgeInsets.all(32),
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Submit Assignment',
                          style: GoogleFonts.inter(
                            fontSize: 24,
                            fontWeight: FontWeight.bold,
                            color: AppColors.textPrimary,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          widget.assignment.title,
                          style: GoogleFonts.inter(
                            fontSize: 16,
                            color: AppColors.textSecondary,
                          ),
                        ),
                        const SizedBox(height: 8),
                        Text(
                          'Attempt ${widget.attemptNumber} of ${widget.assignment.maxAttempts == 0 ? "unlimited" : widget.assignment.maxAttempts}',
                          style: GoogleFonts.inter(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                            color: AppColors.buttonPrimary,
                          ),
                        ),
                      ],
                    ),
                  ),
                  IconButton(
                    onPressed: () => Navigator.of(context).pop(),
                    icon: const Icon(Icons.close),
                  ),
                ],
              ),
              const SizedBox(height: 24),

              // Deadline info
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: isAfterDeadline && !isWithinLateDeadline
                      ? Colors.red.withValues(alpha: 0.1)
                      : isAfterDeadline
                      ? Colors.orange.withValues(alpha: 0.1)
                      : Colors.blue.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                    color: isAfterDeadline && !isWithinLateDeadline
                        ? Colors.red
                        : isAfterDeadline
                        ? Colors.orange
                        : Colors.blue,
                  ),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(
                          isAfterDeadline && !isWithinLateDeadline
                              ? Icons.error
                              : isAfterDeadline
                              ? Icons.warning
                              : Icons.info,
                          color: isAfterDeadline && !isWithinLateDeadline
                              ? Colors.red
                              : isAfterDeadline
                              ? Colors.orange
                              : Colors.blue,
                        ),
                        const SizedBox(width: 8),
                        Text(
                          isAfterDeadline && !isWithinLateDeadline
                              ? 'Deadline Passed'
                              : isAfterDeadline
                              ? 'Late Submission'
                              : 'On Time',
                          style: GoogleFonts.inter(
                            fontSize: 14,
                            fontWeight: FontWeight.bold,
                            color: isAfterDeadline && !isWithinLateDeadline
                                ? Colors.red
                                : isAfterDeadline
                                ? Colors.orange
                                : Colors.blue,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Text(
                      'Deadline: ${_formatDateTime(widget.assignment.deadline)}',
                      style: GoogleFonts.inter(fontSize: 12),
                    ),
                    if (widget.assignment.lateDeadline != null)
                      Text(
                        'Late Deadline: ${_formatDateTime(widget.assignment.lateDeadline!)}',
                        style: GoogleFonts.inter(fontSize: 12),
                      ),
                  ],
                ),
              ),

              const SizedBox(height: 24),

              // Form fields
              Expanded(
                child: SingleChildScrollView(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // File upload section
                      Text(
                        'Upload Files *',
                        style: GoogleFonts.inter(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                          color: AppColors.textPrimary,
                        ),
                      ),
                      const SizedBox(height: 8),

                      // Info about file formats
                      if (widget.assignment.allowedFileFormats.isNotEmpty)
                        Container(
                          padding: const EdgeInsets.all(12),
                          decoration: BoxDecoration(
                            color: Colors.blue.withValues(alpha: 0.1),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: Row(
                            children: [
                              const Icon(
                                Icons.info_outline,
                                size: 16,
                                color: Colors.blue,
                              ),
                              const SizedBox(width: 8),
                              Expanded(
                                child: Text(
                                  'Allowed formats: ${widget.assignment.allowedFileFormats.map((f) => f.toUpperCase()).join(", ")}',
                                  style: GoogleFonts.inter(
                                    fontSize: 12,
                                    color: AppColors.textPrimary,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      const SizedBox(height: 12),

                      // Upload button
                      ElevatedButton.icon(
                        onPressed: _isUploading ? null : _pickAndUploadFiles,
                        icon: _isUploading
                            ? SizedBox(
                                width: 16,
                                height: 16,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  valueColor:
                                      const AlwaysStoppedAnimation<Color>(
                                        Colors.white,
                                      ),
                                  value: _uploadProgress > 0
                                      ? _uploadProgress
                                      : null,
                                ),
                              )
                            : const Icon(Icons.upload_file, size: 18),
                        label: Text(
                          _isUploading
                              ? 'Uploading... ${(_uploadProgress * 100).toStringAsFixed(0)}%'
                              : 'Upload Files',
                          style: GoogleFonts.inter(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppColors.buttonPrimary,
                          foregroundColor: Colors.white,
                          padding: const EdgeInsets.symmetric(
                            horizontal: 24,
                            vertical: 16,
                          ),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),

                      const SizedBox(height: 16),

                      // Paste file URL (optional)
                      Text(
                        'Or add file URL manually',
                        style: GoogleFonts.inter(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                          color: AppColors.textPrimary,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Row(
                        children: [
                          Expanded(
                            child: TextFormField(
                              controller: _fileUrlController,
                              decoration: InputDecoration(
                                filled: true,
                                fillColor: AppColors.background,
                                hintText: 'Paste file URL (optional)',
                                border: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(12),
                                  borderSide: const BorderSide(
                                    color: AppColors.border,
                                  ),
                                ),
                              ),
                            ),
                          ),
                          const SizedBox(width: 8),
                          IconButton(
                            onPressed: _addFileUrl,
                            icon: const Icon(Icons.add),
                            style: IconButton.styleFrom(
                              backgroundColor: AppColors.buttonPrimary,
                              foregroundColor: Colors.white,
                            ),
                          ),
                        ],
                      ),
                      if (_submittedFiles.isNotEmpty) ...[
                        const SizedBox(height: 16),
                        Text(
                          'Files to Submit (${_submittedFiles.length})',
                          style: GoogleFonts.inter(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                            color: AppColors.textPrimary,
                          ),
                        ),
                        const SizedBox(height: 8),
                        ...List.generate(_submittedFiles.length, (index) {
                          final file = _submittedFiles[index];
                          return Container(
                            margin: const EdgeInsets.only(bottom: 8),
                            padding: const EdgeInsets.all(12),
                            decoration: BoxDecoration(
                              color: AppColors.background,
                              borderRadius: BorderRadius.circular(8),
                              border: Border.all(color: AppColors.border),
                            ),
                            child: Row(
                              children: [
                                const Icon(Icons.attach_file, size: 20),
                                const SizedBox(width: 8),
                                Expanded(
                                  child: Text(
                                    file.split('/').last,
                                    style: GoogleFonts.inter(fontSize: 14),
                                    maxLines: 1,
                                    overflow: TextOverflow.ellipsis,
                                  ),
                                ),
                                IconButton(
                                  icon: const Icon(Icons.delete, size: 20),
                                  onPressed: () => _removeFile(file),
                                  color: Colors.red,
                                ),
                              ],
                            ),
                          );
                        }),
                      ],
                    ],
                  ),
                ),
              ),

              // Actions
              const SizedBox(height: 24),
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: _isLoading
                        ? null
                        : () => Navigator.of(context).pop(),
                    child: Text('Cancel', style: GoogleFonts.inter()),
                  ),
                  const SizedBox(width: 12),
                  ElevatedButton(
                    onPressed:
                        _isLoading ||
                            isBeforeStart ||
                            (isAfterDeadline && !isWithinLateDeadline)
                        ? null
                        : _submitAssignment,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.buttonPrimary,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(
                        horizontal: 32,
                        vertical: 16,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: _isLoading
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              valueColor: AlwaysStoppedAnimation<Color>(
                                Colors.white,
                              ),
                            ),
                          )
                        : Text(
                            'Submit Assignment',
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  String _formatDateTime(DateTime date) {
    return '${date.day}/${date.month}/${date.year} ${date.hour.toString().padLeft(2, '0')}:${date.minute.toString().padLeft(2, '0')}';
  }
}
